[server.http]
port = 9004
EnableAccessInterceptor = true
EnableAccessInterceptorReq = true
EnableAccessInterceptorRes = true
AccessInterceptorReqResFilter = '!(request.path.startsWith("/hello") && request.method == "GET")'

[trace]
ServiceName = "server"
